name: CI

# Trigger the workflow on push and pull_request events for the main and dev branches, as well as any other branches.
on:
  push:
    branches:
      - main
      - dev
      - '**'  # Match any branch
  pull_request:
    branches:
      - main
      - dev
      - '**'  # Match any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
