name: NPM Install and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change to WebForAll directory
        run: cd WebForAll

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
