name: NPM Install and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List root directory contents
        run: ls -R

      - name: Change to the correct directory
        run: |
          cd webforall  
          ls -R        

      - name: Run tests
        run: npm test
