name: NPM Install and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List directory contents
        run: ls -R

      - name: Change to WebForAll directory
        run: cd WebForAll

      - name: List directory contents of WebForAll
        run: ls -R

      - name: Run tests
        run: npm test
